[package]
name = "ffi_node"
version = "0.1.0"
edition = "2018"

# FFI for NodeJS
[lib]
name = "ffi_node"
crate-type = ["rlib", "cdylib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
